version: '3.8'
services:
  frontend:
    build: frontend
    ports:
      - 3000:${FRONTEND_PORT}
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8080:${BACKEND_PORT}
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:${MYSQL_PORT}"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Ensure init.sql is in the same directory as docker-compose.yml
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: